@host = http://localhost:3000/api

### Create demande
POST {{host}}/internship
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean@example.com",
  "service": "IT",
  "dateDebut": "2025-11-01",
  "dateFin": "2025-11-30",
  "motivation": "Stage d'observation"
}

### List all demandes
GET {{host}}/internship

### Get demande detail
GET {{host}}/internship/1

### Update status
PATCH {{host}}/internship/2
Content-Type: application/json

{
  "status": "APPROVED"
}

### Delete internship demande
DELETE {{host}}/internship/1
